# Generated by Django 3.1.3 on 2020-12-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseimg', models.ImageField(upload_to='house/')),
                ('price', models.BigIntegerField(default=0)),
                ('address', models.TextField(max_length=100)),
                ('area', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('owner', models.TextField(max_length=200)),
                ('view', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societyamenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenitie', models.CharField(max_length=100)),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bungalow')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bungalow')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseimages1', models.ImageField(upload_to='gallery/')),
                ('houseimages2', models.ImageField(upload_to='gallery/')),
                ('houseimages3', models.ImageField(upload_to='gallery/')),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bungalow')),
            ],
        ),
        migrations.CreateModel(
            name='Fieldvisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bungalow')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_detail', models.TextField(max_length=2000)),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bungalow')),
            ],
        ),
    ]
